server:
  port: 8093
  tomcat:
    connection-timeout: 20000ms
    accept-count: 200
    max-connections: 200
    processor-cache: 200
    threads:
      min-spare: 50
      max: 200
  servlet:
    session:
      timeout: 20m
spring:
  application:
    name: thinkiot-wap
  profiles:
    include: redis,clusterTrue,consumer
  main:
    allow-bean-definition-overriding: true
management:
  endpoint:
    health:
      probes:
        enabled: true