server:
  port: 8089
  tomcat:
    connection-timeout: 20000ms
    accept-count: 200
    max-connections: 200
    processor-cache: 200
    threads:
      min-spare: 50
      max: 200
  servlet:
    session:
      timeout: 240m
spring:
  application:
    name: thinkiot-web
  profiles:
    include: redis,clusterTrue,consumer
  # 引入job会导致有相同名称的bean
  main:
    allow-bean-definition-overriding: true
management:
  endpoint:
    health:
      probes:
        enabled: true
